In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [3]:
# Constant
ESP_final_file = "/content/drive/MyDrive/University /Polito Master/Applied data science project/Project/Datasets/Inflows dataset/ESP_MERGED.csv"
ITA_final_file = "/content/drive/MyDrive/University /Polito Master/Applied data science project/Project/Datasets/Inflows dataset/ITA_MERGED.csv"
GRC_final_file = ""

climate_path_folder = "/content/drive/MyDrive/University /Polito Master/Applied data science project/Project/Datasets/Climate datasets/Climate_datasets_Cleaned"

### ESP FIXING

In [10]:
df_esp = pd.read_csv(ESP_final_file)
df_esp = df_esp[df_esp.columns.drop(list(df_esp.filter(regex='Unnamed')))]
df_esp = df_esp.drop(['Distinct_check', 'Cumulative_arrivals', 'Distinct_columns_check', 'Cumulative_arrivals_by_country_of_arrival'], axis=1)

In [11]:
df_esp.head()

,Reported_Date,ISO3_of_Origin,Monthly_inflow,ISO3_of_Arrival,Min_T,Max_T,Avg_T,mm_Percip
0,2017-12,AFG,2.0,ESP,-4.63,9.43,2.40,17.59
1,2017-12,AGO,4.0,ESP,17.30,28.54,22.89,166.87
2,2017-12,BDI,1.0,ESP,14.66,25.93,20.26,116.02
3,2017-12,BEN,20.0,ESP,20.54,34.28,27.38,1.89
4,2017-12,BFA,350.0,ESP,19.26,33.29,26.25,0.02

In [22]:
# Clean dataset
df_esp = df_esp.query("not Monthly_inflow.isnull()", engine='python')
df_esp = df_esp.query("ISO3_of_Origin != 'OOO' & ISO3_of_Origin != 'OOS'", engine='python')

,Reported_Date,ISO3_of_Origin,Monthly_inflow,ISO3_of_Arrival,Min_T,Max_T,Avg_T,mm_Percip
0,2017-12,AFG,2.0,ESP,-4.63,9.43,2.40,17.59
1,2017-12,AGO,4.0,ESP,17.30,28.54,22.89,166.87
2,2017-12,BDI,1.0,ESP,14.66,25.93,20.26,116.02
3,2017-12,BEN,20.0,ESP,20.54,34.28,27.38,1.89
4,2017-12,BFA,350.0,ESP,19.26,33.29,26.25,0.02
...,...,...,...,...,...,...,...,...
1054,2021-05,YEM,2.0,ESP,NaN,NaN,NaN,NaN
1055,2021-08,YEM,13.0,ESP,NaN,NaN,NaN,NaN
1056,2021-11,YEM,12.0,ESP,NaN,NaN,NaN,NaN
1057,2021-12,YEM,2.0,ESP,NaN,NaN,NaN,NaN
1058,2021-03,ZAF,29.0,ESP,NaN,NaN,NaN,NaN